apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ci
spec:
  acme:
    email: ${email}
    privateKeySecretRef:
      name: le-clusterissuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx