name: 'Terraform GitHub Actions'
on:
  push:
    branches:
    - main
  pull_request:

env:
  TF_VERSION: 1.0.5
  TF_INIT_OPTIONS: -backend-config="access_key=$"
  TF_VALIDATE_OPTIONS: -no-color
  TF_PLAN_OPTIONS: -no-color
  TF_WORKING_DIR: infra
  TF_APPLY_OPTIONS: -auto-approve -no-color
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:

  terraform:
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Terraform Setup'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Terraform Init'
      run: terraform init ${{ env.TF_INIT_OPTIONS }}
      env:
        TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc

    - name: 'Terraform Validate'
      run: terraform validate ${{ env.TF_VALIDATE_OPTIONS }}

    - name: 'Terraform Plan'
      run: terraform plan ${{ env.TF_PLAN_OPTIONS }}

    - name: 'Terraform Apply'
      run: terraform apply ${{ env.TF_APPLY_OPTIONS }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
