name: "Deploy to Azure"

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_VERSION: 1.4.6
  TF_VALIDATE_OPTIONS: -no-color
  TF_PLAN_OPTIONS: -no-color
  TF_WORKING_DIR: app
  TF_APPLY_OPTIONS: -auto-approve -no-color
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  setup:
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: "Terraform Init"
        run: terraform init -backend-config="access_key=tjczAlXO7w1k+4pmNXvP6d1zMYsBQPssnKDQpuXqBor6wDBIXd1UAvwKz/Z4gEKwjyNhTp13NHfU+ASt24HUMQ=="
        env:
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc

      - name: "Terraform Validate"
        run: terraform validate ${{ env.TF_VALIDATE_OPTIONS }}

      - name: "Terraform Plan"
        run: terraform plan ${{ env.TF_PLAN_OPTIONS }}

      - name: "Terraform Apply"
        run: terraform apply ${{ env.TF_APPLY_OPTIONS }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: "Terraform Output"
        run: terraform output -json > config.json
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Upload output to Azure Storage
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az storage blob upload --account-name msprarosaje --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --name config.json --type block --file ./config.json --container-name config

  deploy:
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Download config.json from Azure Storage
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az storage blob download --account-name msprarosaje --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --name config.json --container-name config --file ./config.json

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: "Terraform Init"
        run: terraform init -backend-config="access_key=tjczAlXO7w1k+4pmNXvP6d1zMYsBQPssnKDQpuXqBor6wDBIXd1UAvwKz/Z4gEKwjyNhTp13NHfU+ASt24HUMQ=="
        env:
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc

      - name: "Terraform Validate"
        run: terraform validate ${{ env.TF_VALIDATE_OPTIONS }}

      - name: "Terraform Plan"
        run: terraform plan ${{ env.TF_PLAN_OPTIONS }}

      - name: "Terraform Apply"
        run: terraform apply ${{ env.TF_APPLY_OPTIONS }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
